
sudo: required

language: java

jdk:
  - openjdk11

services:
  - elasticsearch
  - mongodb
    
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.3.deb && sudo dpkg -i --force-confnew elasticsearch-6.4.3.deb && sudo service elasticsearch restart

install:
  - mvn clean verify
