# Use the default network olog_default.
version: "3.9"
services:
  olog:
    build: .
    ports:
      - "8080:8080"
      - "8181:8181"
    depends_on:
      - mongo
      - elastic
    # Ensure that the elastic server is up before starting olog.
    command: wait-for-it -t 30 elastic:9200 -- /bin/sh -c "java -jar olog-es-*.jar --spring.config.name=application-docker"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - olog-mongodata:/etc/mongo
  elastic:
    image: elasticsearch:6.8.13
    environment:
      cluster.name: elasticsearch
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - olog-esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

# Configure persistent storage for mongo and elastic.
volumes:
  olog-esdata:
    driver: local
  olog-mongodata:
    driver: local
